import React from 'react'
import Head from 'next/head'

const Litterature = () => {
    return (
        <>
            <Head>
                <title>Maybewriting - Litterature</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <h1>
                Litterature
            </h1>
        </>
    )
}

export default Litterature
